#!/usr/bin/env bash

tmp=`mktemp`
wget -O$tmp 'https://omahaproxy.appspot.com/all?os=linux&channel=beta'

latest_version=$(awk -F, '{ if ( $11 != "v8_version" ) { print $11 } }' < $tmp)

rm -f $tmp
echo "latest version: $latest_version"

sed -e "s/^\(DEFAULT_VERSION=\).*/\1\"$latest_version\"/" -i support/build/libraries/v8

git update-index -q --ignore-submodules --refresh
git diff-index --quiet HEAD -- && {
	echo ""
	echo "Nothing changed."
	exit 0
}

git commit -a -m "Update latest PHP versions"
