#!/usr/bin/env bash
stack=$1; shift

set -xeo pipefail

docker build --tag heroku-php-build-$stack --file $(pwd)/support/build/_docker/$stack.Dockerfile .

dokku_run() {
  docker run --env-file=env-file -e S3_PREFIX=dist-$stack-develop/ -e UPSTREAM_S3_PREFIX=dist-$stack-stable/ -it heroku-php-build-$stack $*
}

shipit() {
  dokku_run support/build/_util/deploy.sh --overwrite $*
}

shipit libraries/v8


for dir in no-debug-non-zts-20151012 no-debug-non-zts-20160303/; do
  shipit `cd support/build/; ls -1 extensions/$dir/v8js-bare-1.*`
  shipit `cd support/build/; ls -1 extensions/$dir/v8js-1.*`
done

dokku_run support/build/_util/mkrepo.sh --upload
dokku_run support/build/_util/sync.sh heroku-v8js dist-$stack-stable/ 
